/**
 * Generates docs/seo-metadata-map.md and docs/content-inventory.md from the
 * route registry and data files (via the SSR build). Run after `npm run build`.
 */
import { writeFileSync } from 'node:fs';
import path from 'node:path';
import { loadServer, root } from './lib.mjs';

const { routes, fullTitle, headFor, locations, industries, services, packages, outstandingFacts } = await loadServer();
const md = (s) => String(s).replace(/\|/g, '\\|');
const today = new Date().toISOString().slice(0, 10);

// ---- SEO metadata map
let seo = `# SEO metadata map\n\nGenerated by \`npm run docs:generate\` on ${today} from \`src/routes.ts\`. Do not edit by hand.\n\n`;
seo += 'Canonical host: production (`https://bigcatmarketing.com.au`). Staging builds carry the same canonicals but are `noindex, nofollow` and blocked in robots.txt.\n\n';
seo += '| Path | Title | Description | Schema types | Priority |\n|---|---|---|---|---|\n';
for (const r of routes) {
  const h = headFor(r);
  const types = new Set();
  const walk = (n) => {
    if (Array.isArray(n)) n.forEach(walk);
    else if (n && typeof n === 'object') {
      if (n['@type'] && n['@id']) [].concat(n['@type']).forEach((t) => types.add(t));
      if (n['@type'] === 'Offer') types.add('Offer');
      Object.values(n).forEach(walk);
    }
  };
  walk(h.jsonLd);
  seo += `| \`${r.path}\` | ${md(fullTitle(r))} (${fullTitle(r).length}) | ${md(r.description)} (${r.description.length}) | ${[...types].join(', ')} | ${r.priority} |\n`;
}
seo += '\n404: `/404.html` — `noindex`, no canonical, no JSON-LD.\n';
writeFileSync(path.join(root, 'docs', 'seo-metadata-map.md'), seo);

// ---- Content inventory
let inv = `# Content inventory\n\nGenerated by \`npm run docs:generate\` on ${today}. Every field marked **REVIEW** must be checked by someone with genuine local / industry knowledge before production, then the entry's \`reviewStatus\` set to \`'approved'\` in the data file.\n\n`;
inv += '## Business facts (src/data/business.ts)\n\n| Fact | Required for production | Note |\n|---|---|---|\n';
for (const f of outstandingFacts()) inv += `| \`${f.key}\` | ${f.required ? '**YES**' : 'optional'} | ${f.note} |\n`;
inv += '\nAlso outstanding: approved logo (`public/logo.png`, `public/favicon.svg`, `public/apple-touch-icon.png`), share image (`public/og-default.png`), all photography (every "Image placeholder" block), founder/team story on /about, privacy policy + terms legal review, confirm "within 1 business day" response promise.\n\n';

const fieldList = ['suburbs', 'intro', 'landscape', 'searchChallenges', 'relevantServices', 'commonIndustries', 'faqs', 'caseStudies'];
inv += '## Location pages (src/data/locations.ts)\n\n| Page | Status | ' + fieldList.join(' | ') + ' |\n|---|---|' + fieldList.map(() => '---').join('|') + '|\n';
for (const l of locations) {
  inv += `| [${l.name}](${l.path}) | ${l.reviewStatus} | ` + fieldList.map((f) => (l.needsReview.includes(f) ? '**REVIEW**' : f === 'caseStudies' ? (l.caseStudies.length ? String(l.caseStudies.length) : 'none approved') : 'draft')).join(' | ') + ' |\n';
}
inv += '\n"draft" = written generically and safe, but still worth a read. Suburb lists should reflect where the business genuinely wants work.\n\n';

const indFields = ['intro', 'examples', 'searchExamples', 'challenges', 'serviceMapping', 'faqs', 'relatedLocations'];
inv += '## Industry pages (src/data/industries.ts)\n\n| Page | Status | ' + indFields.join(' | ') + ' |\n|---|---|' + indFields.map(() => '---').join('|') + '|\n';
for (const i of industries) {
  inv += `| [${i.name}](/industries/${i.slug}) | ${i.reviewStatus} | ` + indFields.map((f) => (i.needsReview.includes(f) ? '**REVIEW**' : 'draft')).join(' | ') + ' |\n';
}
inv += '\n## Service pages (src/data/services.ts)\n\n| Page | FAQs | Related package |\n|---|---|---|\n';
for (const s of services) inv += `| [${s.name}](/services/${s.slug}) | ${s.faqs.length} | ${s.relatedPackage} |\n`;
inv += '\n## Package pages (src/data/packages.ts)\n\n| Page | Price (ex GST) | Inclusions | Review |\n|---|---|---|---|\n';
for (const p of packages) inv += `| [${p.name} — ${p.theme}](/packages/${p.slug}) | $${p.priceMonthly}/month | ${p.inclusions.length} | Confirm minimum-term wording in FAQ |\n`;
inv += '\n## Case studies (src/data/caseStudies.ts)\n\nNone approved yet. The homepage Proof section and per-region/industry case-study blocks stay hidden until an entry with written client approval is added.\n';
writeFileSync(path.join(root, 'docs', 'content-inventory.md'), inv);
console.log('✔ docs/seo-metadata-map.md and docs/content-inventory.md generated');
