/**
 * Generates dist/.htaccess for Apache / LiteSpeed (cPanel) hosting, mirroring
 * deploy/nginx/*: clean URLs without trailing slash, legacy 301s from
 * redirects.map, 404 page, cache rules, security headers and (non-production)
 * noindex. Run after prerender (needs dist/.csp-inline-hash.txt).
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { dist, loadServer, root } from './lib.mjs';

const { siteConfig } = await loadServer();
const hash = readFileSync(path.join(dist, '.csp-inline-hash.txt'), 'utf8').trim();
const map = readFileSync(path.join(root, 'deploy', 'nginx', 'redirects.map'), 'utf8');
const esc = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
const redirects = [];
for (const line of map.split('\n')) {
  const m = line.trim().match(/^\/(\S*?)\/?\s+(\S+);$/);
  if (m && m[1]) redirects.push(`RewriteRule ^${esc(m[1])}/?$ ${m[2]} [R=301,L]`);
}
const uniq = [...new Set(redirects)];
const csp = `default-src 'self'; script-src 'self' ${hash} https://www.googletagmanager.com; style-src 'self'; img-src 'self' data: https://www.google-analytics.com https://www.googletagmanager.com; font-src 'self'; connect-src 'self' https://www.google-analytics.com https://*.google-analytics.com https://*.analytics.google.com https://www.googletagmanager.com; frame-src https://www.google.com; frame-ancestors 'none'; base-uri 'self'; form-action 'self'; object-src 'none'; upgrade-insecure-requests`;
const prod = siteConfig.env === 'production';
// Host-specific lines (e.g. the AddHandler block cPanel's MultiPHP selector writes) go in
// deploy/apache/htaccess.local and are kept at the top of every generated file.
const localFile = path.join(root, 'deploy', 'apache', 'htaccess.local');
const local = existsSync(localFile) ? readFileSync(localFile, 'utf8').trim() : '';

const out = `# Generated by scripts/htaccess.mjs for the ${siteConfig.env} build — do not edit by hand.
# Apache / LiteSpeed equivalent of deploy/nginx/bigcat-site.conf.
${local ? `\n# --- host-specific (deploy/apache/htaccess.local) ---\n${local}\n# --- end host-specific ---\n` : ''}Options -Indexes -MultiViews
DirectoryIndex index.html
DirectorySlash Off
ErrorDocument 404 /404.html
AddDefaultCharset utf-8
AddType font/woff2 .woff2

<IfModule mod_rewrite.c>
RewriteEngine On

# HTTPS
RewriteCond %{HTTPS} !=on
RewriteCond %{HTTP:X-Forwarded-Proto} !=https
RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
${prod ? '\n# www → apex\nRewriteCond %{HTTP_HOST} ^www\\.bigcatmarketing\\.com\\.au$ [NC]\nRewriteRule ^ https://bigcatmarketing.com.au%{REQUEST_URI} [R=301,L]\n' : ''}
# Never serve private config, dotfiles (except ACME) or build metadata
RewriteRule ^_private(/|$) - [R=404,L]
RewriteCond %{REQUEST_URI} !^/\\.well-known/
RewriteRule (^|/)\\. - [R=404,L]
# API: only the five public endpoints
RewriteCond %{REQUEST_URI} ^/api/
RewriteCond %{REQUEST_URI} !^/api/(contact|checkup|subscribe|health|token)\\.php$
RewriteRule ^ - [R=404,L]

# Legacy URLs (from deploy/nginx/redirects.map)
${uniq.join('\n')}

# Canonical form: no /index.html, no trailing slash
RewriteCond %{THE_REQUEST} \\s/+(\\S*?/)?index\\.html[\\s?]
RewriteRule ^(.*?)/?index\\.html$ /$1 [R=301,L,NE]
RewriteCond %{REQUEST_URI} !^/api/
RewriteRule ^(.+)/$ /$1 [R=301,L]

# Clean URL → prerendered file
RewriteCond %{REQUEST_FILENAME} -d
RewriteCond %{REQUEST_FILENAME}/index.html -f
RewriteRule ^(.+)$ /$1/index.html [L]
</IfModule>

<IfModule mod_headers.c>
Header always set Content-Security-Policy "${csp}"
Header always set Strict-Transport-Security "max-age=31536000; includeSubDomains"
Header always set X-Content-Type-Options "nosniff"
Header always set X-Frame-Options "DENY"
Header always set Referrer-Policy "strict-origin-when-cross-origin"
Header always set Permissions-Policy "camera=(), microphone=(), geolocation=(), payment=(), usb=()"
Header always set Cross-Origin-Opener-Policy "same-origin"
${prod ? '' : 'Header always set X-Robots-Tag "noindex, nofollow"\n'}Header unset X-Powered-By
<FilesMatch "\\.html$">
  Header set Cache-Control "no-cache"
</FilesMatch>
<FilesMatch "\\.(png|jpe?g|webp|avif|svg|ico|woff2?)$">
  Header set Cache-Control "public, max-age=86400"
</FilesMatch>
<FilesMatch "^(sitemap\\.xml|robots\\.txt)$">
  Header set Cache-Control "public, max-age=3600"
</FilesMatch>
<If "%{REQUEST_URI} =~ m#^/assets/#">
  Header set Cache-Control "public, max-age=31536000, immutable"
</If>
</IfModule>

<IfModule mod_deflate.c>
AddOutputFilterByType DEFLATE text/html text/css text/javascript application/javascript application/json image/svg+xml application/xml text/plain
</IfModule>
`;
writeFileSync(path.join(dist, '.htaccess'), out);
console.log(`✔ .htaccess (${uniq.length} legacy redirects, ${siteConfig.env})`);
if (!existsSync(path.join(dist, '404.html'))) console.warn('⚠ 404.html missing');
